# from sqlalchemy.ext.declarative import declarative_base
# from sqlalchemy.orm import Mapped, mapped_column, relationship
# from sqlalchemy import INTEGER

# Base = declarative_base()

# class Weather(Base):
    
#     __tablename__ = 'weather'
#     id: Mapped[int] = mapped_column(primary_key=True)
#     temperature_2m: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     relative_humidity_2m: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     dew_point_2m: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     apparent_temperature: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     pressure_msl: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     surface_pressure: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     cloud_cover: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     cloud_cover_low: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     cloud_cover_mid: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     cloud_cover_high: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     wind_speed_10m: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     wind_speed_80m: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     wind_speed_120m: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     wind_speed_180m: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     wind_direction_10m: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     wind_direction_80m: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     wind_direction_120m: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     wind_direction_180m: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     wind_gusts_10m: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     shortwave_radiation: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     direct_radiation: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     direct_normal_radiation: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     diffuse_radiation: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     global_tilted_irradiance: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     vapour_pressure_deficit: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     cape: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     evapotranspiration: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     et0_fao_evapotranspiration: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     precipitation: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     snowfall: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     precipitation_probability: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     rain: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     showers: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     weather_code: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     snow_depth: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     freezing_level_height: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     visibility: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     soil_temperature_0cm: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     soil_temperature_6cm: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     soil_temperature_18cm: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     soil_temperature_54cm: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     soil_moisture_0_to_1cm: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     soil_moisture_1_to_3cm: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     soil_moisture_3_to_9cm: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     soil_moisture_9_to_27cm: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     soil_moisture_27_to_81cm: Mapped[int] = mapped_column(INTEGER, nullable=False)
#     is_day: Mapped[int] = mapped_column(INTEGER, nullable=False)